name: wifi_iot
description: Flutter plugin which can handle WiFi connections and hotspot (AP, STA)
version: 0.3.19+3
homepage: https://github.com/flutternetwork/WiFiFlutter/tree/master/packages/wifi_iot

flutter:
  plugin:
    androidX: true
    platforms:
      android:
        package: com.alternadom.wifiiot
        pluginClass: WifiIotPlugin
      ios:
        pluginClass: WifiIotPlugin

environment:
  sdk: ^3.8.1
  flutter: ">=1.13.0"

dependencies:
  flutter:
    sdk: flutter
